- https://neptune.ai/blog/image-processing-in-python-algorithms-tools-and-methods-you-should-know
- https://github.com/asztrajman/image_difference
- https://pythonhosted.org/pypotrace/ref.html
- https://discourse.mcneel.com/t/how-to-trace-a-line-drawing-image-to-be-a-real-line-vector-drawing-instead-of-a-outline-image/99934
- https://stackoverflow.com/questions/56673283/how-to-measure-the-angle-between-2-lines-in-a-same-image-using-python-opencv
# TODO expliquer dans les slides les transformées de hough in a nutshell
- https://en.wikipedia.org/wiki/Hough_transform
# pourrait servir pour montrer que ce que j'ai fait sert pas à rien (?????)
- https://castcoverz.com/how-to-know-if-a-bone-is-broken-in-children/
# régler le problème de corrélation seuils / propriétés image
- https://dataanalysis.substack.com/p/correlation-analysis-101-in-python

- datasets:
  - https://stanfordmlgroup.github.io/competitions/mura/

- radiologie portative: https://www.echographes.fr/produit/appareil-de-radiologie-portable-konted-ktx21/ # 6.59 k€... oof

- images:
  - https://coastalurgentcarethibodaux.com/wp-content/uploads/2018/06/signs-of-a-broken-bone.jpeg
  - https://i.stack.imgur.com/YkxJx.jpg
  - épaule_clair: https://www.startradiology.com/uploads/images/english-class-fracture-general-principles-fig3-stress-fracture-pathological-fracture-blanco.jpg
  - https://images.radiopaedia.org/images/1999433/04eef421e99e346d6c5b2abb361b9b.jpg

- classification: 
  - https://radiopaedia.org/articles/garden-classification-of-hip-fractures # petite mine d'or
  - SALTER: https://www.nucleotype.com/salter-harris-fractures/
