- https://neptune.ai/blog/image-processing-in-python-algorithms-tools-and-methods-you-should-know
- https://github.com/asztrajman/image_difference
- https://pythonhosted.org/pypotrace/ref.html
- https://discourse.mcneel.com/t/how-to-trace-a-line-drawing-image-to-be-a-real-line-vector-drawing-instead-of-a-outline-image/99934
- https://stackoverflow.com/questions/56673283/how-to-measure-the-angle-between-2-lines-in-a-same-image-using-python-opencv
- https://en.wikipedia.org/wiki/Hough_transform
